# cpu_throttle.cmake — keeps Ninja/Make from saturating the dev machine.
#
# IMPORTANT: a build's job count is decided by the *build* invocation
# (`cmake --build` / `ninja`), which is a separate process from this configure
# step. Mutating ENV here would NOT affect it. So instead we:
#   1. compute a safe job count (cores - headroom) and a load cap (~0.8*cores),
#   2. expose them as cache variables for tooling/presets, and
#   3. GENERATE an executable wrapper `${CMAKE_BINARY_DIR}/throttled-build.sh`
#      that runs the real, throttled build:  cmake --build . -j N -- -l LOAD
# Use it:  ./build/<preset>/throttled-build.sh [extra cmake --build args]

if(NOT DEFINED DETR_CPU_HEADROOM)
  set(DETR_CPU_HEADROOM 2 CACHE STRING
      "Cores to keep free for the OS / other work while building")
endif()

include(ProcessorCount)
ProcessorCount(_detr_cores)
if(_detr_cores EQUAL 0)
  set(_detr_cores 1)
endif()

math(EXPR _detr_jobs "${_detr_cores} - ${DETR_CPU_HEADROOM}")
if(_detr_jobs LESS 1)
  set(_detr_jobs 1)
endif()

# Ninja/Make -l load cap: suspend launching new jobs while load average is at or
# above this. ~80% of cores keeps the machine responsive.
math(EXPR _detr_load_cap "(${_detr_cores} * 8) / 10")
if(_detr_load_cap LESS 1)
  set(_detr_load_cap 1)
endif()

set(DETR_RECOMMENDED_JOBS "${_detr_jobs}" CACHE STRING
    "Recommended -j for builds (cores - headroom)" FORCE)
set(DETR_NINJA_LOAD_CAP "${_detr_load_cap}" CACHE STRING
    "Recommended -l load cap for ninja/make" FORCE)

# Generate the wrapper that ACTUALLY throttles the build (uses generator
# expressions so paths are correct per build config).
if(CMAKE_GENERATOR MATCHES "Ninja" OR CMAKE_GENERATOR MATCHES "Makefiles")
  file(GENERATE
    OUTPUT "${CMAKE_BINARY_DIR}/throttled-build.sh"
    CONTENT "#!/bin/sh
# Generated by cpu_throttle.cmake — throttled build to keep the machine usable.
# Caps parallelism at ${_detr_jobs} jobs and suspends new jobs above load ${_detr_load_cap}.
exec cmake --build \"${CMAKE_BINARY_DIR}\" -j ${_detr_jobs} \"$@\" -- -l ${_detr_load_cap}
"
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE
  )
  message(STATUS
    "detrcpp: throttled build wrapper -> ${CMAKE_BINARY_DIR}/throttled-build.sh "
    "(-j ${_detr_jobs} -l ${_detr_load_cap} of ${_detr_cores} cores).")
else()
  message(STATUS
    "detrcpp: throttle advisory only for generator '${CMAKE_GENERATOR}'. "
    "Recommended: cmake --build ... -j ${_detr_jobs}.")
endif()
